pool/urls.py
from django.conf.urls import url
from django.contrib import admin
from pools import views 
import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^$', views.index, name='home'),
    url(r'^cadastro/', views.person,name='cadastro' ),
    url(r'^grato/', views.thanks,name='grato' ),
    url(r'^pesquisa/(?P<person>[\w\-]+)/$', views.poll,name='pesquisa' ),
    url(r'^pesquisa/(?P<person>[\w\-]+)/(?P<p>[\w\-]+)/$', views.poll_id,name='pesquisa' ),
    url(r'^$', views.index, name='pesquisa'),
] + static(settings.STATIC_URL)

pools/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

TRANSPORT = (
            ('T','Transporte público'),
            ('U','Táxi, Uber ou similares'),
            ('B','Bicicleta'),
            ('V','Veículo próprio'),
            ('N','Não utilizo veículos'),
            )
VOTE = (
        (-5,'-5'),
        (-4,'-4'),
        (-3,'-3'),
        (-2,'-2'),
        (-1,'-1'),
        (0,'0'),
        (1,'1'),
        (2,'2'),
        (3,'3'),
        (4,'4'),
        (5,'5'),
        )
TYPE= (
        ('S','Select'),
        ('T', 'Texto livre'),
        ('M', 'Multipla Escolha'),
        ('A', 'Ambos'),
    )

class Pool(models.Model):

    name = models.CharField(max_length=200)
    expire = models.DateField(null=True)
    active = models.BooleanField(default=True)
    def __unicode__(self):
        return self.name


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    poll = models.ForeignKey(Pool)
    question_type = models.CharField(max_length=1,choices=TYPE)
    min_value= models.CharField(max_length=200, default=None,blank=True, null=True)
    max_value= models.CharField(max_length=200, default=None,blank=True, null=True)
    def __unicode__(self):
        return self.poll.name +" - " + self.question_text

class MultipleChoice(models.Model):
    question = models.ForeignKey(Question)
    choice = models.CharField(max_length=200)
    def __unicode__(self):
        return self.question.poll.name + " - " + self.question.question_text +" - "+ self.choice
class Person(models.Model):

    name = models.CharField(max_length=200)
    email = models.EmailField(unique=True)
    cell = models.CharField(max_length=200, null=True,blank=True, unique=True)
    birth = models.CharField(max_length=20,null=True,blank=True)
    transport = models.CharField(max_length=1,choices=TRANSPORT)
    accept_spam = models.BooleanField(default=True)
    accept_wzap = models.BooleanField(default=True)
    def __unicode__(self):
        return self.name + " - " + self.email



class Choice(models.Model):
    choice = models.IntegerField(default=0,choices=VOTE, null=True,blank=True)
    free_text = models.CharField(max_length=2000, null=True,blank=True)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    multiple = models.TextField(null=True)

    def create(self,question,person, choice=None,free_text=None,multiple=None):
        self.person=person
        self.question=question
        self.choice=choice
        self.free_text=free_text
        self.multiple=multiple
        self.save()

 

pools/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist as DoesNotExist
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.forms import BaseModelFormSet
from django.forms import ModelForm,DateInput,DateField, Textarea,EmailField
from django.forms import modelformset_factory
from django.utils.translation import ugettext_lazy as _
from models import Person, Pool, VOTE, Choice,Question
from dateutil.parser import parse
DATE_INPUT_FORMATS=('%d-%m-%Y','%d/%m/%y','%Y/%m/%d','%d%m%Y','%d%m%y')


class PersonForm(ModelForm):

    class Meta:
        model=Person
        TST=('%d-%m-%Y','%d/%m/%Y','%Y/%m/%d')
        #exclude=['birth']
        fields='__all__'#('name','email','cell','birth','transport','accept_spam','accept_wzap')
        birth=DateField(input_formats=DATE_INPUT_FORMATS)
        labels={
            'name':_('nome'),
            'email':_('E-mail'),
            'cell':_('telefone'),
            'birth':_('data de nascimento'),
            'transport':_('meio de transporte para chegar a dicez'),
            'accept_spam':_('aceito receber e-mail de promoções da DiceZ'),
            'accept_wzap':_('aceito receber sms e contato por WhatsApp de promoções da DiceZ'),
        }
        
@csrf_exempt
def poll_html(pool,request,p):
    if request.method == 'POST':
        form= request.POST
        try:
            p=Person.objects.get(id=p)
        except DoesNotExist as e:
            print e
            return redirect('/cadastro/')
        
        for choice in form.iteritems():
            c=None
            t=None
            m=None
            if choice[0] not in ['person','csrfmiddlewaretoken']:
                q=Question.objects.get(id=int(choice[0]))
                
                if q.question_type=='S':
                    c=int(choice[1])
                if q.question_type=='T':
                    t=choice[1]
                if q.question_type=='M':
                    m=request.POST.getlist(choice[0])
                     
                if q.question_type=='A':
                    print choice[0]
                    t=form[choice[0]]
                    m=request.POST.getlist(choice[0])
                    print t, m, form['4']
                Choice().create(q,p,c,t,m)
            po=Pool.objects.filter(id__gt=p.id, active=True)
        if po:
            return redirect('/pesquisa/'+str(p[0].id))
        return redirect('/grato')
    questions = pool.question_set.all()
    quests=[]
    count =0
    for q in questions:
        min_value=''
        max_value=''
        if q.min_value:
            min_value=q.min_value
        if q.max_value:
            max_value=q.max_value
        quests.append({'question_text':q.question_text,'id':q.id, 'min_value':min_value,'max_value':max_value})
        if q.question_type in ['S']:
            quests[count]['choice']=VOTE
        if q.question_type in ['M','A']:
            quests[count]['choices']= q.multiplechoice_set.all()
        if q.question_type in ['T','A']:
            quests[count]['text']='S'
        count += 1
    return render(request,'questions.html',{'questions':quests,'person':p})


@csrf_exempt
def poll(request,person):
    polls = Pool.objects.filter(active=True)
    if not polls:
        return redirect('/')
    return poll_html(polls[0],request,person)

def thanks(request):
    return render(request,'grato.html')

@csrf_exempt
def poll_id(request,person,p):
    polls = Pool.objects.filter(active=True, id=p)
    if not polls:
        return redirect('/grato')
    poll=polls[0]
    return poll_html(poll,request,person)

     
    


def person(request):
    form = PersonForm()
    if request.method == 'POST':
        form = PersonForm(request.POST)
        #form.data['birth']=parse(form.data['birth'])
        #print(form.data['birth'])
        #form.save()
        if form.is_valid():
            form.save()
            p=Person.objects.filter(email=form.data['email'])
            if p:

                return redirect('/pesquisa/'+str(p[0].id))
        else:
            p=Person.objects.filter(Q(email=form.data['email']) | Q(cell=form.data['cell']))
            if p:
                return redirect('/pesquisa/'+str(p[0].id))
            print form.errors
            return render(request, 'create_person.html', {'form': form})
    else:

        return render(request, 'create_person.html', {'form': form})

def index(request):
    return render(request, 'index.html')


# Create your views here.

pools/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% block cabecalho %}
        <title>DiceZ</title>
    {% endblock %}
    {% block css %}
    <link rel="stylesheet" type="text/css" href="/static/dicez.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% endblock %}
    
</head>
<body>
    {% block top %}
<div class="container">
<a href="/"><div name="logo" class="logo">
<img src="/static/logo_white.png"/>
</div>
</a> 

    {% endblock %}
    {% block corpo %}
        <!-- body -->
    {% endblock %}
</div>

    <script src="/static/bootstrap-formhelpers-phone.js"></script>
    <script src="/static/bootstrap-formhelpers-phone.format.js"></script>
</body>
</html>

pools/templates/create_person.html
{% extends 'base.html' %}

{% block corpo %}
    <h1>Cadastro</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        <div class="form-group">
            <label for="id_name">
                <h3>nome:</h3>
            </label>
            <input id="id_name" maxlength="200" name="name" class="form-control input-lg" type="text" required >
        </div>
        <div class="form-group"><label for="id_email"><h3>e-mail:</h3></label> <input id="id_email" maxlength="254" name="email" type="email" class="form-control input-lg" required /></div>
        <div class="form-group"><label for="id_cel"><h3>telefone:</h3></label> <input id="id_cell" name="cell" type="text" class="form-control input-lg bfh-phone" data-format="(dd)ddddd-dddd"></div>
        <div class="form-group"><label for="id_birth"><h3>data de nascimento:</h3></label> <input id="id_birth" maxlength="20" name="birth" type="date" class="form-control input-lg" /></div>
        <div class="form-group">
            <label for="id_transport">
                <h3>meio de transporte para chegar a dicez:</h3>
            </label>
                <select id="id_transport" name="transport" class="form-control input-lg" required>
                    <option value="" selected="selected">---------</option>
                    <option value="T">Transporte público</option>
                    <option value="U">Táxi, Uber ou similares</option>
                    <option value="B">Bicicleta</option>
                    <option value="V">Veículo próprio</option>
                    <option value="N">Não utilizo veículos</option>
                </select>
        </div>
        <div class="checkbox">
            <label for="id_accept_spam">
                <h3>
                    <input checked="checked" id="id_accept_spam" name="accept_spam" type="checkbox" />aceito receber e-mail de promoções da DiceZ.
                </h3>
            </label>
        </div>
        <div class="checkbox"><label for="id_accept_wzap"><h3><input checked="checked" id="id_accept_wzap" name="accept_wzap" type="checkbox"/><h3>aceito receber sms e contato por WhatsApp de promoções da DiceZ.</h3></label></div>

        <button type="submit" class="save btn btn-default">continuar</button>
    </form>
{% endblock %}

pools/templates/grafico.html
{% extends "base.html" %}
{% load humanize %}
  {% block cabecalho %}
      <script type="text/javascript">
  window.onload = function () {
    var chart = new CanvasJS.Chart("chartContainer",
    {
      zoomEnabled: false,
                        animationEnabled: true,
      title:{
        text: "valores"
      },
      axisY2:{
        valueFormatString:"0.0 \%",
        
        maximum:{{max_value}},
        interval: {{interval}},
        interlacedColor: "#F5F5F5",
        gridColor: "#D7D7D7",      
        tickColor: "#D7D7D7"                
      },
                        theme: "theme2",
                        toolTip:{
                                shared: true
                        },
      legend:{
        verticalAlign: "bottom",
        horizontalAlign: "center",
        fontSize: 15,
        fontFamily: "Lucida Sans Unicode"

      },
      data: [
       {% for fundo in fundos_list %}

               {        
          type: "line",
          lineThickness:3,
          axisYType:"secondary",
          showInLegend: true,           
          name: "{{fundo.nome}}", 
          dataPoints: [
          {% for rentabilidade in fundo.rentabilidades %}
          { x: new Date({{rentabilidade.date|date:"Y,m-1,d"}}), y: {{rentabilidade.value}}/{{fundo.menor_valor}}-1 },
          {% endfor %}
          ]
          },

    {% endfor %}


        ]
     ,
          legend: {
            cursor:"pointer",
            itemclick : function(e) {
              if (typeof(e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
              e.dataSeries.visible = false;
              }
              else {
                e.dataSeries.visible = true;
              }
              chart.render();
            }
          }
        });

chart.render();
}
</script>
  <script type="text/javascript" src="/static/js/canvasjs.min.js"></script>
  {% endblock %}


{% block corpo %}

    <div id="chartContainer" style="height: 400px; width: 70%; margin-left:10%">
   </div>
    <table border="1"; margin-left:10%>
    <tr>
    <th>
    Datas
    </th>    
    {% for date in dates %}
      <th>{{date|date:"d/m/Y"}}</th>
    {% endfor %}
    </tr>

     {% for fundo  in fundos_list %}
     <tr>
     <th><a href="/fundos/{{fundo.id_fundo}}" target="_blank">{{fundo.nome}}</a></th>
      {% for mensal in fundo.mensais%}

      <td>{{mensal.value|floatformat:2|intcomma}}%</td>
     {%endfor%}
     </tr>
     {%endfor%}
    </table>
{% endblock %}

pools/templates/grato.html
{% extends "base.html" %}

{% block corpo %}

<br>Todas as perguntas foram respondidas, Grato!</br>
{% endblock %}

pools/templates/index.html
{% extends "base.html" %}

{% block corpo %}
<div class="primero">
    <br><br>
    <p>A Dicez completou seus primeiros seis meses de abertura! Para comemorar, convidamos você a responder uma pequena pesquisa de satisfação. Assim você ajuda a gente a melhorar cada vez mais o nosso serviço e atendimento, e de quebra ainda concorre a um jantar na faixa*. Vamos lá?</p>
</div>
<a href="cadastro">SEGUIR</a>
<br>
<br>


<h6>* Todas as pessoas que preencherem nosso cadastro e completarem a pesquisa concorrerão a um jantar na DiceZ, com direito a: dois lanches, uma porção, dois drinks ou soft drinks e duas sobremesas, sendo todos os itens à escolha do cardápio da DiceZ. O valor do jantar não poderá ser convertido em dinheiro. O sorteio ocorrerá no dia 01/08/2017 e o nome da pessoa ganhadora será divulgado em nossas redes sociais e site. O prazo para retirada do brinde é 31/10/2017, durante os dias e horários de funcionamento normal da DiceZ.
</h6>
{% endblock %}

pools/templates/questions.html
{% extends "base.html" %}

{% block corpo %}
<form method="POST" class="post-form">{% csrf_token %}
<input type="hidden" name="person" value="{{person}}">
    {% for q in questions %}

    <b>{{ q.question_text }}</b><br>

    {%if q.choice %}
        {{q.min_value}}&nbsp;&nbsp;
        {% for k,v in q.choice%} 
            <input type="radio" name="{{q.id}}" value={{v}}> {{k}}</select>&nbsp;&nbsp;
        
        {% endfor %}
        {{q.max_value}}
    <br><br>    
    {% endif %}
    {%if q.choices %}
     <div class="form-group">
               
        {% for v in q.choices%}
                    <div class='bullet'> 
                        <input type="checkbox" name="{{q.id}}" value="{{v.id}}-{{v.choice}}"> {{v.choice}}</select></div>
               
        {% endfor %}
         </div>
    {% endif %}
    {%if q.text %} 
            <div class="form-group">
                <input type="text" name="{{q.id}}"/><br>
            </div>
    {% endif %}
    {% endfor %}
     <button type="submit" class="save btn btn-default">continuar</button>
</form>
{% endblock %}